#!/usr/bin/env bash
# ============================================================
# scripts/gen-secrets.sh —— 生成 controller-protocol 编译期密钥
# ============================================================
#
# 用途：为生产 build 生成两个 32 字节高熵密钥，输出 .env 风格文本。
#
# 用法：
#   1. 输出到 stdout（推荐先预览）：
#        ./scripts/gen-secrets.sh
#   2. 直接写入 .env（会覆盖！先确认 .env 已 git-ignore）：
#        ./scripts/gen-secrets.sh > .env
#   3. 一次性 export 到当前 shell（临时 build 用）：
#        eval "$(./scripts/gen-secrets.sh --export)"
#        cargo make protocol-production-check
#
# 生成算法：`openssl rand -hex 16` → 32 字符十六进制 = 32 字节
# 十六进制字符集 [0-9a-f] 都是可打印 ASCII，无 NUL 字节，
# 满足 build.rs 对密钥的所有约束。

set -euo pipefail

if ! command -v openssl >/dev/null 2>&1; then
  echo "error: 'openssl' not found in PATH" >&2
  exit 1
fi

# --export 模式：生成可直接被 eval 的 export 语句
if [[ "${1:-}" == "--export" ]]; then
  echo "export CONTROLLER_SECRET_V1=$(openssl rand -hex 16)"
  echo "export CONTROLLER_SECRET_V2=$(openssl rand -hex 16)"
  exit 0
fi

# 默认模式：.env 风格
cat <<EOF
# Auto-generated by scripts/gen-secrets.sh at $(date -u +%FT%TZ)
# NEVER commit this file. Keep it secret; keep it safe.
CONTROLLER_SECRET_V1=$(openssl rand -hex 16)
CONTROLLER_SECRET_V2=$(openssl rand -hex 16)
EOF
